name: CI

on: [push]
jobs: 
  Linter-Build-Test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Linter
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm run test